### PR TITLE
Changed DetectLangauge to DetectLanguage in the docs and code

### PR DESCRIPTION
**Pull request by ItzSpex**
This PR fixes issue #21 
This is my first PR for an open-source repository.
I hope I did it right :)

### CODE REVIEW

**Comment by BigicecreamTaken** [comment]
Good job, and thank you for helping this library to grow.
I am happy to tell you are the first contributor outside of Superwise(the company that backs up this library) that opened a PR.

There are a few technical changes that should be made:

1. change to commit name to `chore(elemeta): Changed DetectLangauge to DetectLanguage in the docs and code`
2. run the formatters script: [formatters.sh](https://github.com/superwise-ai/elemeta/blob/main/scripts/formatters.sh)

Add those changes to your commit, and it will be ready to be merged😄

We are going to add a page on [how to contribute](https://github.com/superwise-ai/elemeta/pull/27) very soon

**Comment by ItzSpex** [comment]
What is the version of isort that you use? For some reason, it doesn't recognize the line length parameter:
isort: error: unrecognized arguments: --line-length 99

**Comment by BigicecreamTaken** [comment]
isort=5.12.0
black=22.12.0

I tried running `scripts/formatters.sh` on your last commit and I get:
```
usage: isort [-h] [-V] [--vn] [-v] [--only-modified] [--dedup-headings] [-q] [-d] [--overwrite-in-place] [--show-config] [--show-files] [--df] [-c] [--ws] [--sp SETTINGS_PATH] [--cr CONFIG_ROOT]
             [--resolve-all-configs] [--profile PROFILE] [--old-finders] [-j [JOBS]] [--ac] [--interactive] [--format-error FORMAT_ERROR] [--format-success FORMAT_SUCCESS] [--srx]
             [--filter-files] [-s SKIP] [--extend-skip EXTEND_SKIP] [--sg SKIP_GLOB] [--extend-skip-glob EXTEND_SKIP_GLOB] [--gitignore] [--ext SUPPORTED_EXTENSIONS]
             [--blocked-extension BLOCKED_EXTENSIONS] [--dont-follow-links] [--filename FILENAME] [--allow-root] [-a ADD_IMPORTS] [--append] [--af] [--rm REMOVE_IMPORTS] [--float-to-top]
             [--dont-float-to-top] [--ca] [--cs] [-e] [--ff] [--fgw [FORCE_GRID_WRAP]] [-i INDENT] [--lbi LINES_BEFORE_IMPORTS] [--lai LINES_AFTER_IMPORTS] [--lbt LINES_BETWEEN_TYPES]
             [--le LINE_ENDING] [--ls] [--lss]
             [-m {GRID,VERTICAL,HANGING_INDENT,VERTICAL_HANGING_INDENT,VERTICAL_GRID,VERTICAL_GRID_GROUPED,VERTICAL_GRID_GROUPED_NO_COMMA,NOQA,VERTICAL_HANGING_INDENT_BRACKET,VERTICAL_PREFIX_FROM_MODULE_IMPORT,HANGING_INDENT_WITH_PARENTHESES,BACKSLASH_GRID,0,1,2,3,4,5,6,7,8,9,10,11}]
             [-n] [--nis] [--ot] [--dt] [--rr] [--reverse-sort] [--sort-order SORT_ORDER] [--sl] [--nsl SINGLE_LINE_EXCLUSIONS] [--tc] [--up] [-l LINE_LENGTH] [--wl WRAP_LENGTH]
             [--case-sensitive] [--remove-redundant-aliases] [--honor-noqa] [--treat-comment-as-code TREAT_COMMENTS_AS_CODE] [--treat-all-comment-as-code] [--formatter FORMATTER] [--color]
             [--ext-format EXT_FORMAT] [--star-first] [--split-on-trailing-comma] [--sd DEFAULT_SECTION] [--only-sections] [--ds] [--fas] [--fss] [--hcss] [--srss] [--fass] [-t FORCE_TO_TOP]
             [--combine-straight-imports] [--nlb NO_LINES_BEFORE] [--src SRC_PATHS] [-b KNOWN_STANDARD_LIBRARY] [--extra-builtin EXTRA_STANDARD_LIBRARY] [-f KNOWN_FUTURE_LIBRARY]
             [-o KNOWN_THIRD_PARTY] [-p KNOWN_FIRST_PARTY] [--known-local-folder KNOWN_LOCAL_FOLDER] [--virtual-env VIRTUAL_ENV] [--conda-env CONDA_ENV]
             [--py {all,2,27,3,310,311,36,37,38,39,auto}]
             [files ...]
isort: error: unrecognized arguments: 
All done! ✨ 🍰 ✨
46 files left unchanged.

```
Is this the error you are getting?

If yes, I think it happens because of some whitespaces added to the script.
I recommend you reset to your old commit and rerun the script.

**Comment by ItzSpex** [comment]
I think I resolved the issue by installing the correct versions, I would recommend adding a requirement file for these sorts of things for future contributors.

**Review by BigicecreamTaken — APPROVED** [review]
Looks amazing 🤩 

Thank you for helping 😄

**Pull request merged**
